package co.edu.uniquindio.compiladores.lexico

enum class Categoria {

        ENTERO,
        REAL,
        CARACTER,
        IDENTIFICADOR,
        CADENA_CARACTERES,
        CADENA_CARACTERES_SIN_CERRAR,
        OPERADOR_ARTIMETICO,
        PALABRA_RESERVADA,
        OPERADOR_RELACIONAL,
        OPERADOR_LOGICO,
        OPERADOR_DE_ASIGNACION,
        OPERADOR_DE_INCREMENTO_DECREMENTO,
        PARENTESIS_APERTURA_CIERRE,
        LLAVE_APERTURA_CIERRE,
        TERMINAL_FIN_SENTENCIA,
        SEPARADOR,
        COMENTARIO_DE_LINEA,
        COMENTARIO_DE_BLOQUE,
        COMENTARIO_DE_BLOQUE_SIN_CERRAR,
        DESCONOCIDO
}